name: Image Build
on:
  push:
    branches:
      - main
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: '3 3 * * *' # Daily 3:03 UTC

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  image-build:
    name: Image Build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Ensure repository name is lowercase
        run: |
          $repoName = $env:IMAGE_NAME.ToLower()
          Write-Host "SET environment variable [ 'REPO_NAME' ] TO [ '${repoName}' ]"
          Out-File -InputObject "REPO_NAME=${repoName}" -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0 # https://github.com/docker/setup-qemu-action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0 # https://github.com/docker/setup-buildx-action

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0 # https://github.com/docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: try1
        uses: docker/build-push-action@v6.3.0 # https://github.com/docker/build-push-action
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}:latest
        timeout-minutes: 15
